/* Fake customization */
/* Generated by JTB 1.5.3 (BaseNodesGenerator) */
package org.jtb_th_jcc.eg5.ast;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.NoSuchElementException;
import org.jtb_th_jcc.eg5.Token;
import org.jtb_th_jcc.eg5.vis.IGenVisitor;

@SuppressWarnings("javadoc")
public class NodeToken implements INode, java.io.Serializable {
  
  private static final long serialVersionUID = 1L;
  
  public NodeToken() {
    /* empty */
  }
  
  public List<Token> specialTokens;
  
  public Token getSpecialAt(final int i) {
    if (specialTokens == null) {
      throw new NoSuchElementException("No specialTokens in token"); //$NON-NLS-1$
    }
    return specialTokens.get(i);
  }
  
  public int numSpecials() {
    if (specialTokens == null) {
      return 0;
    }
    return specialTokens.size();
  }
  
  public void addSpecial(final Token s) {
    if (specialTokens == null) {
      specialTokens = new ArrayList<>();
    }
    specialTokens.add(s);
  }
  
  public void trimSpecials() {
    if (specialTokens == null) {
      return;
    }
    ((ArrayList<Token>) specialTokens).trimToSize();
  }
  
  public String getSpecials(final String spc) {
    if (specialTokens == null) {
      return ""; //$NON-NLS-1$
    }
    int stLastLine = -1;
    final StringBuilder buf = new StringBuilder(64);
    boolean hasEol = false;
    for (final Iterator<Token> e = specialTokens.iterator(); e.hasNext();) {
      final Token st = e.next();
      final char c = st.image.charAt(st.image.length() - 1);
      hasEol = c == '\n' || c == '\r';
      if (stLastLine != -1) {
        // not first line
        if (stLastLine != st.beginLine) {
          // if not on the same line as the previous
          for (int i = stLastLine + 1; i < st.beginLine; i++) {
            // keep blank lines
            buf.append(LS);
          }
          buf.append(spc);
        } else { // on the same line as the previous
          // on the same line as the previous
          buf.append(' ');
        }
      }
      buf.append(st.image);
      if (!hasEol && e.hasNext()) {
        // not a single line comment and not the last one
        buf.append(LS);
      }
      stLastLine = st.endLine;
    }
    // keep the same number of blank lines before the current non special
    for (int i = stLastLine + (hasEol ? 1 : 0); i < ((Token) this).beginLine; i++) {
      buf.append(LS);
      if (i != ((Token) this).beginLine - 1) {
        buf.append(spc);
      }
    }
    // indent if the current non special is not on the same line
    if (stLastLine != ((Token) this).beginLine) {
      buf.append(spc);
    }
    return buf.toString();
  }
  
  public String withSpecials(final String spc) {
    return withSpecials(spc, null);
  }
  
  public String withSpecials(final String spc, final String var) {
    final String specials = getSpecials(spc);
    int len = specials.length() + 1;
    if (len == 1) {
      return (var == null ? ((Token) this).image : var + ((Token) this).image);
    }
    if (var != null) {
      len += var.length();
    }
    StringBuilder buf = new StringBuilder(len + ((Token) this).image.length());
    buf.append(specials);
    // see if needed to add a space
    int stLastLine = -1;
    if (specialTokens != null) {
      for (Token e : specialTokens) {
        stLastLine = e.endLine;
      }
    }
    if (stLastLine == ((Token) this).beginLine) {
      buf.append(' ');
    }
    if (var != null) {
      buf.append(var);
    }
    buf.append(((Token) this).image);
    return buf.toString();
  }
  
  /*
   * Visitors accept methods (no -novis option, visitors specification : Gen,void,java.lang.String)
   */
  
  @Override
  public void accept(final IGenVisitor vis, final String argu) {
    vis.visit(this, argu);
  }
  
}
